version: '2.4'

x-limits: &limits
    pids_limit: 1024
    cpu_shares: 256
    mem_limit: 512m
    logging:
        options:
            max-size: 10m
            max-file: '3'

services:
    # rackdns:
    #     <<: *limits
    #     build: ./dns
    #     image: pentest/private.dns
    #     restart: unless-stopped
    #     networks:
    #         default:
    #             ipv4_address: 172.30.0.2

    exploiter:
        <<: *limits
        build: ./exploiter
        image: pentest/private.exploiter
        restart: unless-stopped
        networks:
            default:
                ipv4_address: 172.30.0.2

    rack1:
        <<: *limits
        build: ./racks/rack1
        image: pentest/private.rack1
        restart: unless-stopped
        ports:
          - 2121:0021
        networks:
            default:
                ipv4_address: 172.30.0.3

    web-server:
        <<: *limits
        build: ./web-server
        image: pentest/private.web-server
        restart: unless-stopped
        ports: 
          - 5000:5000
        dns: 
          - rackdns
        networks:
            default:
                ipv4_address: 172.30.0.8
        depends_on:
            - rack1


networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.30.0.0/28