version: '2.4'

x-limits: &limits
    pids_limit: 1024
    cpu_shares: 256
    mem_limit: 512m
    logging:
        options:
            max-size: 10m
            max-file: '3'

services:
    # rackdns:
    #     <<: *limits
    #     build: ./dns
    #     image: pentest/private.dns
    #     restart: unless-stopped
    #     networks:
    #         default:
    #             ipv4_address: 172.30.0.2

    # ns:
    #     <<: *limits
    #     build: ./ns
    #     networks:
    #         default:
    #             ipv4_address: 172.30.0.2
    #     environment:
    #         ZONE_DOMAIN: home.drive
    #         ZONE_HOSTS: rack1=172.30.35.2
    #         ZONE_HOSTS: rack2=172.30.35.3
    #         ZONE_HOSTS: rack3=172.30.35.4
    #         ZONE_HOSTS: rack4=172.30.35.5
    #         ZONE_HOSTS: rack5=172.30.35.6
    #     restart: unless-stopped

    exploiter:
        <<: *limits
        build: ./exploiter
        image: pentest/private.exploiter
        restart: unless-stopped
        networks:
            default:
                ipv4_address: 172.30.0.14

    rack1:
        <<: *limits
        build: ./racks
        image: pentest/private.rack1
        restart: unless-stopped
        ports:
          - 2121:0021
        networks:
            default:
                ipv4_address: 172.30.0.3

    web-server:
        <<: *limits
        build: ./web-server
        image: pentest/private.web-server
        restart: unless-stopped
        ports: 
          - 5000:5000
        dns: 
          - rackdns
        networks:
            default:
                ipv4_address: 172.30.0.8


## TODO hidden network
# external_links: 
#     - shared_gitlab_1: gitlab

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.30.0.0/28